/*
BOOK, AUTHOR, BOOK_SALES

2022년 1월 "판매" 데이터
저자별, 카테고리별 매출액 (TOTAL_SALES = 판매량 * 판매가)

AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES

AUTHOR_ID ASC, CATEGORY DESC
BOOK_SALES의 SALES_DATE이 2022-01-01 ~ 2022-01-31
            BOOK_ID를 기준으로 SALES를 합쳐야함.
*/

SELECT A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * B.TS) AS TOTAL_SALES
FROM BOOK AS A
JOIN (
        SELECT BOOK_ID, SUM(SALES) AS TS
        FROM BOOK_SALES
        WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
        GROUP BY BOOK_ID
) AS B ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS C
  ON A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.CATEGORY, C.AUTHOR_NAME
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC
