/*
CART_PRODUCTS

NAME이 Milk, Yogurt -> 동시에 구매한 장바구니 (CART_ID)

GROUP BY CART_ID?

*/
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
ORDER BY CART_ID;
