/*
ITEM_INFO, ITEN_TREE
더이상 업글 못하는 ITEM_ID, ITEM_NAME, RARITY 출력

업글 못한다는게 무슨 의미? -> 리프노드 의미
리프 노드를 어떻게 찾을 수 있지?
PARENT_ITEM_ID에 안나온 ITEM_ID를 찾으면 되지 않을까?
ITEM_ID NOT IN (PARENT_ITEM_ID -> DISTINCT)
*/

# 1. 리프노드 서브쿼리
# SELECT DISTINCT(PARENT_ITEM_ID)
# FROM ITEM_TREE
# WHERE PARENT_ITEM_ID IS NOT NULL

# 2. NOT IN 쿼리 (메인 쿼리)
SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE AS A
INNER JOIN ITEM_INFO AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.ITEM_ID NOT IN 
(
    SELECT DISTINCT(PARENT_ITEM_ID)
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY A.ITEM_ID DESC
# 3. ITEM_INFO와 JOIN -> 어떤 JOIN을 쓸지. INNER JOIN 해도 충분