/*
ONLINE_SALE / OFFLINE_SALE

2022 3 오프, 온라인 둘다

OFFLINE의 USER_ID는 NULL로 표시

판매일 기준 오름차순, 상품ID 오름차순, USER_ID 오름차순

ONLINE, OFFLINE를 합쳐야함. -> UNION ALL? 
*/

SELECT DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d'), A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
FROM(
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE
    ) AS A
WHERE A.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31' 
ORDER BY A.SALES_DATE ASC, A.PRODUCT_ID ASC, USER_ID ASC