/*
ANIMAL_INS
ANIMAL_OUTS

입양 간 동물 중 보호기간 가장 길었던 동물 2마리 (아이디, 이름)

OUTS에 있는 것들. -> RIGHT JOIN (INNER JOIN도 됨)
DATETIME 차이가 가장 큰것.

-> OUTS에 있는데 INS에 없는거도 있음. -> INNER JOIN

*/


SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY (O.DATETIME - I.DATETIME) DESC
LIMIT 2