/*
CAR_RENTAL_COMPANY_CAR
CAR_RENTAL_COMPANY_RENTAL_HISTORY
CAR_RENTAL_COMPANY_DISCOUNT_PLAN

자동차 종류가 '세단, SUV' / 2022-11-1 ~ 2022-11-30까지 가능
대여금액 50~200미만
*/
SELECT CAR.CAR_ID, CAR.CAR_TYPE, 
    ROUND(CAR.DAILY_FEE * 30 * (1-PLAN.DISCOUNT_RATE/100))
    AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR

LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS 
ON CAR.CAR_ID = HIS.CAR_ID AND (CAR.CAR_TYPE = 'SUV' OR CAR.CAR_TYPE = '세단')
AND NOT(HIS.END_DATE < '2022-11-01' OR HIS.START_DATE > '2022-11-30')

JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN 
ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'

WHERE HIS.CAR_ID IS NULL
GROUP BY CAR.CAR_ID, CAR.CAR_TYPE, CAR.DAILY_FEE, PLAN.DISCOUNT_RATE
HAVING ROUND(CAR.DAILY_FEE * 30 * (1-PLAN.DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC