# CAR_RENTAL_COMPANY_CAR 
# -> CAR_TYPE('세단', 'SUV', ...)
# CAR_RENTAL_COMPANY_RENTAL_HISTORY
# -> 
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#
# 자동차가 '세단', 'SUV'인 자동차 중
# 2022.11.1 ~ 2022.11.30 까지 대여 가능
# 대여 금액이 50~200미만 
# 자동차 ID, 자동차 종류, 대여 금액(FEE) 리스트
# 대여 금액 기준 내림차순 정렬, 대여 금액 같으면 자동차 종류 오름차순
# 자동차 ID기준 내림차순

/*
1. CAR_RENTAL_COMPANY_DISCOUNT_PLAN에서 DURATION_TYPE이 "30일 이상" 인것만 남기기 WHERE
2. CAR_RENTAL_COMPANY_RENTAL_HISTORY에서 START_DATE가 2022-11-1보다 작고 END_DATE가 2022-11-30보다 작은거
3. 
*/






SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * 30 / 100 * (100-B.DISCOUNT_RATE)) AS FEE
FROM (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS A
    WHERE NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    WHERE H.CAR_ID = A.CAR_ID
      AND H.START_DATE <= '2022-11-30'
      AND H.END_DATE >= '2022-11-01'
)
) AS A
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상" 
      AND (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
) AS B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE (A.DAILY_FEE * 30 / 100 * (100-B.DISCOUNT_RATE)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC