/*
REST_INFO

음식 종류별로 즐겨찾기수가 가장 많은 식당
음식종류, ID, 식당 이름, 즐겨찾기수

FOOD_TYPE으로 GROUP BY
*/

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS SQ
ON RI.FOOD_TYPE = SQ.FOOD_TYPE AND RI.FAVORITES = SQ.FAVORITES
ORDER BY FOOD_TYPE DESC