/*
ECOLI_DATA 

1. SIZE_OF_COLONY의 퍼센트 비율에 따라서 4가지로 분류
2. ID와 4가지 분류한걸 COLONY_NAME으로 바꿔서 정리

퍼센트로 분류 어떻게?
그리고 총 데이터 개수는 4의 배수긴 한데 총 데이터 개수를 어떻게 확인? COUNT?

*/

SELECT 
    ID, 
    CASE
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 >= 0 AND PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 <= 25 THEN "CRITICAL"
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 > 25 AND PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 <= 50 THEN "HIGH"
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 > 50 AND PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100 <= 75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC