/*
ECOLI_DATA
대장균 크기 구분
AVG가 아니라 SIZE_OF_COLONY가 전체중에 몇퍼센튼지 묻는거

*/

SELECT ID, 
    CASE
        WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) BETWEEN 0 AND 0.25 THEN 'CRITICAL'
        WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) BETWEEN 0.25 AND 0.5 THEN 'HIGH'
        WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) BETWEEN 0.5 AND 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC