/*
REST_INFO, REST_REVIEW

서울 위치
리뷰 평균점수는 소수점 세번째에서 반올림


*/

SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
  FROM REST_INFO AS RI
  JOIN REST_REVIEW AS RR
    ON RI.REST_ID = RR.REST_ID
 WHERE LEFT(RI.ADDRESS, 2) = '서울'
 GROUP BY RI.REST_ID # REST_ID로 모아서 평균 점수 구해야함.
 ORDER BY SCORE DESC, RI.FAVORITES DESC
