/*
USER_INFO, ONLINE_SALE

USER_INFO의 GENDER는 0 1 NULL
NULL은 제외

년 월 성별 별로 상품을 구매한 회원수 집계
GROUP BY 3개

1. GENDER에서 NULL이 아닌것만 -> IS NOT NULL
*/

SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
  FROM USER_INFO AS UI
  JOIN ONLINE_SALE AS OS
    ON UI.USER_ID = OS.USER_ID
 WHERE UI.GENDER IS NOT NULL
 GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
 ORDER BY YEAR ASC, MONTH ASC, GENDER ASC