/*
대장군 개체 크기 100 이하면 LOW
101~1000 MEDIUM
1001~ HIGH
ID와 SIZE 출력 -> ID ASC
*/

SELECT ID, (CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
            WHEN SIZE_OF_COLONY > 100 AND SIZE_OF_COLONY <= 1000 THEN 'MEDIUM' 
           ELSE 'HIGH' END)
AS SIZE
FROM ECOLI_DATA
ORDER BY ID
