/*
공간을 2개 이상 등록한 사람을 조회
COUNT(HOST_ID) >= 2인 사람만 조회
SUB QUERY + IN 조합 (WHERE)
*/

SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
SELECT HOST_ID 
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(HOST_ID) >= 2
    )