/*
CAR_RENTAL_COMPANY_CAR CAR_RENTAL_COMPANY_RENTAL_HISTORY CAR_RENTAL_COMPANY_DISCOUNT_PLAN 

자동차 종류가 '트럭'인 대여기록에 대해 대여기록별 금액(FEE) 구해서 대여 기록ID, 대여 금액 리스트 출력
*/


SELECT HIS.HISTORY_ID, 
        FLOOR(
            (DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1) *
            CAR.DAILY_FEE *
            (100- IFNULL(REPLACE(DIS.DISCOUNT_RATE, "%", ""), 0)) / 100 
        ) AS FEE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
JOIN CAR_RENTAL_COMPANY_CAR AS CAR 
    ON HIS.CAR_ID = CAR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DIS 
    ON CAR.CAR_TYPE = DIS.CAR_TYPE
    AND DIS.DURATION_TYPE = 
    CASE
      WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 90 THEN '90일 이상'
      WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 30 THEN '30일 이상'
      WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 7 THEN '7일 이상'
      ELSE NULL
    END
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HIS.HISTORY_ID DESC;