/*
PATIENT / DOCTOR / APPOINTMENT

2022/4/13 취소X인 흏부외과(CS) 진료 예약 내역

APPOINTMENT / APNT_YMD, APNT_NO, PT_NO, MCDP_CD
APNT_YMD가 2022-04-13>= 이고 APNT_CNCL_YN이 N이고 MCDP_CD가 CS


*/

SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS B ON A.PT_NO = B.PT_NO
JOIN DOCTOR AS C ON A.MDDR_ID = C.DR_ID
WHERE YEAR(A.APNT_YMD) = '2022' AND MONTH(A.APNT_YMD) = '04' AND DAY(A.APNT_YMD) = '13'
 AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD ASC