/*
0~23시 입양 몇건

*/

WITH RECURSIVE HOURS AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM hours WHERE HOUR < 23
)



SELECT H.HOUR, COUNT(HOUR(AO.DATETIME)) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN HOURS AS H
ON H.HOUR = HOUR(AO.DATETIME)
GROUP BY H.HOUR
