/*
SKILLCODES
DEVELOPERS

FRONT END 스킬을 가진 개발자의 정보 조회

CATEGORY가 FRONT END인 사람
어떻게 하지 이거?
SKILL_CODE를 계속 2로 나눠야함.
*/

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES AS S
JOIN DEVELOPERS AS D
    ON (D.SKILL_CODE & S.CODE) != 0
WHERE S.CATEGORY = 'Front End'
ORDER BY D.ID ASC