/*
USED_GOODS_BOARD
USED_GOODS_USER

완료된 중고거래 총 금액이 70만원 이상이 사람
회원 ID, 닉네임, 총 거래금액
SUM -> AVG
*/

SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID AND B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC

