/*
완료된 중고거래의 출금액이 70만원 이상인 사람 (USER_ID, NICKNAME, 총 거래금액)
1. USER_GOODS_BOARD에서 WRITER_ID로 GROUP BY 진행
    -> SUM(PRICE) AS TP  -> 이거 2개
2. 이거랑 USED_GOODS_USER하고 JOIN
3. USER_ID, NICKNAME, TP 출력
*/

SELECT A.WRITER_ID, B.NICKNAME, A.TP AS TOTAL_SALES
FROM USED_GOODS_USER AS B
INNER JOIN (
SELECT WRITER_ID, SUM(PRICE) AS TP
FROM USED_GOODS_BOARD
WHERE STATUS LIKE 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
) AS A
ON A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES ASC
