/*
HR_DEPARTMENT

HR_EMPLOYEES

HR_GRADE
사원별 성과금

GROUP BY EMP_NO, EMP_NAME
-> AVG(SCORE) -> 이거에 따라서 GRADE가 나옴. CASE WHEN THEN END 사용
-> BONUS는 GRADE에 따라서 나옴. -> GRADE처럼 CASE문 쓰고 거기에 SUM(SAL)/COUNT 하기
*/

SELECT 
    EMPL.EMP_NO, 
    EMPL.EMP_NAME,
    CASE
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(sCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN AVG(SCORE) >= 96 THEN EMPL.SAL * 0.2
        WHEN AVG(SCORE) >= 90 THEN EMPL.SAL * 0.15
        WHEN AVG(SCORE) >= 80 THEN EMPL.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_DEPARTMENT AS DEPT
JOIN HR_EMPLOYEES AS EMPL ON DEPT.DEPT_ID = EMPL.DEPT_ID
JOIN HR_GRADE AS GRAD ON EMPL.EMP_NO = GRAD.EMP_NO
GROUP BY EMPL.EMP_NO, EMPL.EMP_NAME
ORDER BY EMPL.EMP_NO ASC