/*
HR_DEPARTMENT / HR_EMPLOYEES / HR_GRADE

사원별 성과금 정보
평가 점수별 등급, 등급에 따른 성과금

EMP_NO	EMP_NAME	GRADE	BONUS


*/

 SELECT 
  HRE.EMP_NO, 
  HRE.EMP_NAME,
  CASE
    WHEN SUM(HRG.SCORE) / COUNT(HRG.HALF_YEAR) >= 96 THEN 'S'
    WHEN SUM(HRG.SCORE) / COUNT(HRG.HALF_YEAR) >= 90 THEN 'A'
    WHEN SUM(HRG.SCORE) / COUNT(HRG.HALF_YEAR) >= 80 THEN 'B'
    ELSE 'C'
  END AS GRADE,
  CASE
    WHEN SUM(HRG.SCORE) / COUNT(HRG.HALF_YEAR) >= 96 THEN HRE.SAL * 20 / 100
    WHEN SUM(HRG.SCORE) / COUNT(HRG.HALF_YEAR) >= 90 THEN HRE.SAL * 15 / 100
    WHEN SUM(HRG.SCORE) / COUNT(HRG.HALF_YEAR) >= 80 THEN HRE.SAL * 10 / 100
    ELSE 0
  END AS BONUS
  FROM HR_EMPLOYEES AS HRE
  JOIN HR_GRADE AS HRG
    ON HRE.EMP_NO = HRG.EMP_NO
 GROUP BY HRG.EMP_NO # COUNT(HALF_YEAR), SUM(SCORE)
 ORDER BY HRE.EMP_NO ASC
 