/*
1. 리뷰를 가장 많이 작성한 회원들 -> 1명의 회원?
2. 이 회원들의 모든 리뷰 조회
*/

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS A
JOIN MEMBER_PROFILE AS B
    ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID = 
(
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY(MEMBER_ID)
ORDER BY COUNT(MEMBER_ID) DESC
LIMIT 1
)

ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC