/*
CAR_RENTAL_COMPANY_RENTAL_HISTORY

2022 8 ~ 2022 10 -> 총 대여 횟수가 5회 이상인 자동차들
월별 자동차 ID별 총 대여횟수 (RECORDS)
자동차 ID별? -> 1월에 1번차가 몇번 대여 -> 이느낌
0인 것은 제외

WHERE 2022 8 ~ 2022 10
GROUP BY CAR_ID
-> 5회 이상인 자동차만 나옴

위 서브쿼리를 통해서 CAR_ID만 뽑을 수 있음
*/

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND 
    CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC