/*
1. 대여 시작일 기준 2022 8 ~ 2022 10까지 총 대여횟수가 5회 이상인 자동차
2. 총 대여횟수(RECORDS)를 출력
3. 월 기준 오름차순, 자동차 기준 내림차순 / MONTH, CAR_ID

0. START_DATE가 2022-8 ~ 2022-10인거만 남기기
1. GROUP BY(CAR_ID) -> COUNT(CAR_ID) >= 5인거만 남기기
*/

    
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
