/*
FISH_INFO

물고기 종류별로 가장 큰 물고기
FISH_TYPE 별로 가장 큰 물고기

GROUP FISH_TYPE
MAX(LENGTH)
이걸로 SQ?

*/

SELECT INFO.ID, NAME.FISH_NAME, INFO.LENGTH
FROM FISH_INFO AS INFO
JOIN (
    SELECT I.FISH_TYPE, MAX(I.LENGTH) AS MX, N.FISH_NAME
    FROM FISH_INFO AS I
    JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY I.FISH_TYPE, N.FISH_NAME
) AS NAME 
ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE NAME.MX = INFO.LENGTH
ORDER BY INFO.ID ASC
