SELECT G.SCORE,
       E.EMP_NO,
       E.EMP_NAME,
       E.POSITION,
       E.EMAIL
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO,
           SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) G
ON E.EMP_NO = G.EMP_NO
WHERE G.SCORE = (
    SELECT MAX(SCORE_SUM)
    FROM (
        SELECT SUM(SCORE) AS SCORE_SUM
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) T
)
ORDER BY E.EMP_NO;
