/*
HR_DEPARTMENT

HR_EMPLOYEES

부서별 평균 연봉 조회하기
평균 연봉은 소수점 첫째 자리에서 반올림(AVG_SAL) -> DESC

*/

SELECT A.DEPT_ID, A.DEPT_NAME_EN, ROUND(AVG(B.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS A
INNER JOIN HR_EMPLOYEES AS B
ON A.DEPT_ID = B.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC
