
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
SELECT FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(GREATEST(LENGTH, 10)) >= 33
# ORDER BY AVG(GREATEST(LENGTH, 10)) DESC;
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC